import { useMemo, useState } from 'react';
import {
  AlertCircle,
  BookOpenText,
  Building2,
  Check,
  ChevronDown,
  Clock,
  Code2,
  FileText,
  Loader2,
} from 'lucide-react';
import type { AgentContextDocument } from '../../../api/agents';
import { cn } from '../../../lib/utils';

/**
 * Renders the compiler-generated knowledge documents as human-readable
 * cards instead of raw markdown. The compiler wraps every block in
 * `<!-- section:name:start/end -->` markers, so we can split documents
 * into titled sections and render facts as structured rows.
 */

type ParsedSection = { id: string; body: string };

const SECTION_LABELS: Record<string, string> = {
  identity: 'Identity',
  about: 'About the business',
  hours: 'Business hours',
  services: 'Services & pricing',
  booking: 'Booking requirements',
  'urgent-rules': 'Transfer & urgent rules',
  role: 'Agent role',
  rules: 'Call rules',
  conversion: 'Conversion style',
};

const DOC_META: Record<string, { title: string; blurb: string; icon: typeof FileText }> = {
  business_profile: {
    title: 'Business Profile',
    blurb: 'The facts your agent quotes to callers — address, hours, services, pricing.',
    icon: Building2,
  },
  agent_playbook: {
    title: 'Agent Playbook',
    blurb: 'The behavior rules your agent follows on every call.',
    icon: BookOpenText,
  },
};

const parseSections = (content: string): ParsedSection[] => {
  const sections: ParsedSection[] = [];
  const re = /<!-- section:([\w-]+):start -->([\s\S]*?)<!-- section:\1:end -->/g;
  let match: RegExpExecArray | null;
  while ((match = re.exec(content)) !== null) {
    const body = match[2].trim();
    if (body) sections.push({ id: match[1], body });
  }
  if (sections.length === 0 && content.trim()) {
    sections.push({ id: 'content', body: content.trim() });
  }
  return sections;
};

/** Line-level renderer: bullets become lists, "Key: Value" becomes fact rows. */
const SectionBody = ({ body }: { body: string }) => {
  const lines = body
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('_Generated by') && !/^#{1,2}\s/.test(line));

  return (
    <div className="space-y-1">
      {lines.map((line, i) => {
        if (line.startsWith('- ')) {
          return (
            <div key={i} className="flex items-start gap-2 text-sm leading-6 text-slate-700">
              <Check size={13} className="mt-1.5 shrink-0 text-emerald-500" />
              <span>{line.slice(2)}</span>
            </div>
          );
        }
        const kv = line.match(/^([A-Za-z][\w\s&]{0,30}):\s+(.+)$/);
        if (kv) {
          return (
            <div key={i} className="flex items-baseline gap-2 text-sm leading-6">
              <span className="w-24 shrink-0 text-xs font-semibold uppercase tracking-wide text-slate-400">
                {kv[1]}
              </span>
              <span className="min-w-0 flex-1 break-words text-slate-800">{kv[2]}</span>
            </div>
          );
        }
        return (
          <p key={i} className="text-sm leading-6 text-slate-700">
            {line}
          </p>
        );
      })}
    </div>
  );
};

const StatusPill = ({ doc }: { doc: AgentContextDocument }) => {
  switch (doc.ingest_status) {
    case 'ready':
      return (
        <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700">
          <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" /> Live
        </span>
      );
    case 'pending':
    case 'ingesting':
      return (
        <span className="inline-flex items-center gap-1 rounded-full bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-700">
          <Loader2 size={11} className="animate-spin" /> Updating…
        </span>
      );
    case 'error':
      return (
        <span
          className="inline-flex items-center gap-1 rounded-full bg-red-50 px-2 py-1 text-xs font-semibold text-red-700"
          title={doc.ingest_error || undefined}
        >
          <AlertCircle size={11} /> Failed
        </span>
      );
    default:
      return (
        <span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-500">
          {doc.ingest_status}
        </span>
      );
  }
};

const relativeTime = (iso?: string) => {
  if (!iso) return '';
  const then = new Date(iso).getTime();
  if (Number.isNaN(then)) return '';
  const mins = Math.floor((Date.now() - then) / 60000);
  if (mins < 1) return 'just now';
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
};

const DocCard = ({ doc, open, onToggle }: { doc: AgentContextDocument; open: boolean; onToggle: () => void }) => {
  const meta = DOC_META[doc.doc_type] || {
    title: doc.title || doc.filename,
    blurb: '',
    icon: FileText,
  };
  const Icon = meta.icon;
  const sections = useMemo(() => parseSections(doc.content), [doc.content]);
  const [showRaw, setShowRaw] = useState(false);

  return (
    <div className="overflow-hidden">
      <button
        type="button"
        onClick={onToggle}
        aria-expanded={open}
        className="flex w-full items-center justify-between gap-4 px-4 py-3 text-left transition hover:bg-slate-50"
      >
        <div className="flex min-w-0 items-center gap-3">
          <div
            className={cn(
              'flex h-9 w-9 shrink-0 items-center justify-center rounded-lg',
              doc.ingest_status === 'ready' ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-100 text-slate-400'
            )}
          >
            <Icon size={16} />
          </div>
          <div className="min-w-0">
            <p className="truncate text-sm font-semibold text-slate-900">{meta.title}</p>
            <p className="truncate text-xs text-slate-500">{meta.blurb || doc.filename}</p>
          </div>
        </div>
        <div className="flex shrink-0 items-center gap-3">
          {doc.updated_at && (
            <span className="hidden items-center gap-1 text-xs text-slate-400 sm:inline-flex">
              <Clock size={11} /> {relativeTime(doc.updated_at)}
            </span>
          )}
          <StatusPill doc={doc} />
          <ChevronDown size={15} className={cn('text-slate-400 transition-transform', open && 'rotate-180')} />
        </div>
      </button>

      {open && (
        <div className="border-t border-slate-100 bg-slate-50/60 px-4 py-4">
          {doc.ingest_status === 'error' && doc.ingest_error && (
            <div className="mb-3 rounded-lg border border-red-100 bg-red-50 px-3 py-2 text-xs font-medium text-red-700">
              {doc.ingest_error}
            </div>
          )}

          <div className="grid gap-3 lg:grid-cols-2">
            {sections.map((section) => (
              <div key={section.id} className="rounded-lg border border-slate-200 bg-white p-3.5">
                <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-400">
                  {SECTION_LABELS[section.id] || section.id.replaceAll('-', ' ')}
                </p>
                <SectionBody body={section.body} />
              </div>
            ))}
          </div>

          <button
            type="button"
            onClick={() => setShowRaw((v) => !v)}
            className="mt-3 inline-flex items-center gap-1.5 text-xs font-semibold text-slate-400 transition hover:text-slate-600"
          >
            <Code2 size={12} />
            {showRaw ? 'Hide raw markdown' : 'View raw markdown'}
          </button>
          {showRaw && (
            <pre className="mt-2 max-h-[320px] overflow-auto whitespace-pre-wrap rounded-lg bg-slate-950 p-4 text-xs leading-5 text-slate-100">
              {doc.content}
            </pre>
          )}
        </div>
      )}
    </div>
  );
};

export const GeneratedContext = ({
  docs,
  lastCompiledAt,
}: {
  docs: AgentContextDocument[];
  lastCompiledAt: string;
}) => {
  const [openId, setOpenId] = useState('');

  return (
    <section className="rounded-xl border border-slate-200 bg-white">
      <div className="flex items-center justify-between border-b border-slate-100 px-4 py-3">
        <div className="flex items-center gap-2">
          <FileText size={17} className="text-slate-400" />
          <div>
            <h2 className="text-sm font-semibold text-slate-900">What your agent knows</h2>
            <p className="text-xs text-slate-400">Compiled automatically from your Business Profile</p>
          </div>
        </div>
        <span className="shrink-0 text-xs font-medium text-slate-400">
          {lastCompiledAt ? `Compiled ${relativeTime(lastCompiledAt)}` : `${docs.length} files`}
        </span>
      </div>

      <div className="divide-y divide-slate-100">
        {docs.length === 0 ? (
          <div className="p-8 text-center text-sm text-slate-400">
            Nothing compiled yet. Press “Recompile context” to build your agent’s knowledge from the Business
            Profile.
          </div>
        ) : (
          docs.map((doc) => (
            <DocCard key={doc.id} doc={doc} open={openId === doc.id} onToggle={() => setOpenId(openId === doc.id ? '' : doc.id)} />
          ))
        )}
      </div>

      {docs.length > 0 && (
        <p className="border-t border-slate-100 px-4 py-2.5 text-[11px] leading-4 text-slate-400">
          Update your details in <a href="/dashboard/business-details" className="font-semibold text-blue-500 hover:underline">Business Profile</a>, then press “Recompile context” to refresh what the agent says on calls.
        </p>
      )}
    </section>
  );
};
